from mmaseq.utils.PATH import *
from mmaseq.utils import logging_setup, helpers, sample_config, result_paths, results_aggregator
from pathlib import Path
import pandas as pd

# Initiate logging
###################################################################
logger = logging_setup.initiate_log("MMAseq Pipeline")
logging_setup.adjust_log(logger, int(config["verbosity"]))

logger.info("Setting up pipeline variables")
logger.debug("Importing user input from config file")


# Read user input
###################################################################
samplesheet_path = Path(config["samplesheet"])
outdir = Path(config["outdir"])
ignore_assemblies = config["ignore_assemblies"]
deploy_dir = Path(config["deploy_dir"])
spe_configs_dir = Path(config["spe_configs_dir"])

logger.trace(("User input (by config):\n"
    f" - samplesheet_path: {samplesheet_path}"
    f" - deploy_dir: {deploy_dir}"
    f" - outdir: {outdir}"))

# Deduce variables
###################################################################
logdir = outdir / "Logs"
database_dir = deploy_dir / "Databases"
logger.trace(("Deduced variables:\n"
    f" - logdir: {logdir}"
    f" - database_dir: {database_dir}"))


# Read config files
#################################################################
logger.debug("Creating sample specific input and output objects")
logger.trace("Reading samplesheet")
samplesheet = pd.read_csv(samplesheet_path, 
                          sep='\t').set_index("sample_name")

logger.trace("Reading result files catalogue")
results_catalogue = helpers.read_results_catalogue(CATALOGUE_PATH)

logger.trace("Defining sample specific configurations")
sample_configs = sample_config.determine_sample_configs(samplesheet, 
                                                           spe_configs_dir, 
                                                           ignore_assemblies)

all_result_files = result_paths.define_all_result_files(outdir, 
                                                        sample_configs, 
                                                        results_catalogue)

all_result_filepaths = [
    path
    for sample in all_result_files.values()
    for files in sample.values()
    for path in files
]

logger.info("Initiating pipeline")


# Define the dynamic input for rule all
###################################################################
rule all:
    input:
        all = all_result_filepaths
    output:
        all = "%s/results_long.tsv" %outdir
    run:
        all_results_long = results_aggregator.generate_long_results(all_result_files)
        all_results_long.to_csv(output.all, sep = "\t")


include : "rules/db_fetch.smk"      
include : "rules/db_setup.smk"       
include : "rules/assemblers.smk"
include : "rules/mappers.smk"
include : "rules/variant_calling.smk"
include : "rules/screening.smk"
include : "rules/typing.smk"
include : "rules/custom_analysis.smk"



